### ISSUE TITLE
Please update to version used in openhab binding

### ISSUE THREAD

**Issue by dimalo** [coasterli/YeelightLib#1]
hi @coasterli, it seems that the version used in the openhab binding is newer than the one in this repo. please push your changes (increase-decrease actions etc.)

cheers!

**Comment by kubawolanin** [comment]
@coasterli could you please update it here?
This will unblock [your Pull Request](https://github.com/openhab/openhab2-addons/pull/1514) and potentially there might be someone who's willing to finish up your work.
Looking forward to hear from you.
Best regards
